name: Flutter Format Check

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run format check
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze
